<?php

namespace Tests\Feature;

use App\Models\InventoryItem;
use App\Models\Project;
use App\Models\StockBalance;
use App\Models\StockLocation;
use App\Models\Tenant;
use App\Services\AuthService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class InventoryItemTest extends TestCase
{
    use RefreshDatabase;

    private function loginAsStorekeeper(): Tenant
    {
        $tenant = Tenant::create([
            'name' => 'Inventory Co',
            'slug' => 'inventory-co',
        ]);

        app(AuthService::class)->createUser($tenant, [
            'name' => 'Store Keeper',
            'email' => 'store@test.local',
            'password' => 'password',
            'role' => 'Storekeeper',
        ]);

        tenancy()->end();

        $this->post('/login', [
            'email' => 'store@test.local',
            'password' => 'password',
        ])->assertRedirect('/dashboard');

        return $tenant;
    }

    private function createStore(Tenant $tenant): StockLocation
    {
        tenancy()->initialize($tenant);

        $project = Project::create([
            'code' => 'PRJ-001',
            'name' => 'Main Site',
            'client' => 'Client',
            'location' => 'Dar',
            'contract_amount' => '1000000',
            'wht_percentage' => '5',
            'net_budget' => '950000',
            'physical_progress_pct' => '0',
            'start_date' => now()->toDateString(),
            'end_date' => now()->addYear()->toDateString(),
            'status' => 'active',
        ]);

        $location = StockLocation::create([
            'name' => 'Main Store',
            'project_id' => $project->id,
        ]);

        tenancy()->end();

        return $location;
    }

    public function test_storekeeper_can_view_inventory_items_page(): void
    {
        $this->loginAsStorekeeper();

        $this->get('/inventory/items')
            ->assertOk()
            ->assertInertia(fn ($page) => $page
                ->component('Inventory/Items')
                ->has('items')
                ->has('categories')
                ->has('stock_locations')
            );
    }

    public function test_storekeeper_can_create_inventory_item_with_autogenerated_code(): void
    {
        $tenant = $this->loginAsStorekeeper();

        $this->post('/inventory/items', [
            'name' => 'Portland Cement 50kg',
            'unit' => 'bag',
            'category' => 'materials',
            'reorder_point' => '100',
        ])->assertRedirect();

        tenancy()->initialize($tenant);

        $this->assertDatabaseHas('inventory_items', [
            'code' => 'PC-50KG',
            'name' => 'Portland Cement 50kg',
            'unit' => 'bag',
            'category' => 'materials',
        ]);

        $item = InventoryItem::query()->where('code', 'PC-50KG')->first();
        $this->assertNotNull($item);
        $this->assertSame('100.000', (string) $item->reorder_point);

        tenancy()->end();
    }

    public function test_storekeeper_can_create_item_with_opening_stock(): void
    {
        $tenant = $this->loginAsStorekeeper();
        $location = $this->createStore($tenant);

        $this->post('/inventory/items', [
            'name' => 'Portland Cement 50kg',
            'unit' => 'bag',
            'category' => 'materials',
            'opening_quantity' => '40',
            'stock_location_id' => $location->id,
            'unit_cost' => '18500',
        ])->assertRedirect();

        tenancy()->initialize($tenant);

        $item = InventoryItem::query()->where('code', 'PC-50KG')->firstOrFail();
        $this->assertDatabaseHas('stock_balances', [
            'inventory_item_id' => $item->id,
            'stock_location_id' => $location->id,
            'quantity_on_hand' => '40.000',
        ]);

        tenancy()->end();
    }

    public function test_storekeeper_can_receive_stock(): void
    {
        $tenant = $this->loginAsStorekeeper();
        $location = $this->createStore($tenant);

        tenancy()->initialize($tenant);
        $item = InventoryItem::create([
            'code' => 'PC-50KG',
            'name' => 'Portland Cement 50kg',
            'unit' => 'bag',
            'category' => 'materials',
        ]);
        tenancy()->end();

        $this->post('/inventory/receive', [
            'inventory_item_id' => $item->id,
            'stock_location_id' => $location->id,
            'quantity' => '25',
            'unit_cost' => '18000',
        ])->assertRedirect();

        tenancy()->initialize($tenant);

        $balance = StockBalance::query()
            ->where('inventory_item_id', $item->id)
            ->where('stock_location_id', $location->id)
            ->first();

        $this->assertNotNull($balance);
        $this->assertSame('25.000', (string) $balance->quantity_on_hand);

        tenancy()->end();
    }

    public function test_storekeeper_can_create_stock_location(): void
    {
        $tenant = $this->loginAsStorekeeper();

        tenancy()->initialize($tenant);
        $project = Project::create([
            'code' => 'PRJ-LOC',
            'name' => 'Yard Project',
            'client' => 'Client',
            'location' => 'Dar',
            'contract_amount' => '1000000',
            'wht_percentage' => '5',
            'net_budget' => '950000',
            'physical_progress_pct' => '0',
            'start_date' => now()->toDateString(),
            'end_date' => now()->addYear()->toDateString(),
            'status' => 'active',
        ]);
        tenancy()->end();

        $this->post('/inventory/locations', [
            'name' => 'Site Store A',
            'project_id' => $project->id,
        ])->assertRedirect();

        tenancy()->initialize($tenant);

        $this->assertDatabaseHas('stock_locations', [
            'name' => 'Site Store A',
            'project_id' => $project->id,
        ]);

        tenancy()->end();
    }

    public function test_autogenerated_code_gets_suffix_when_base_exists(): void
    {
        $tenant = $this->loginAsStorekeeper();

        tenancy()->initialize($tenant);
        InventoryItem::create([
            'code' => 'PC-50KG',
            'name' => 'Existing Cement',
            'unit' => 'bag',
            'category' => 'materials',
        ]);
        tenancy()->end();

        $this->post('/inventory/items', [
            'name' => 'Portland Cement 50kg',
            'unit' => 'bag',
            'category' => 'materials',
        ])->assertRedirect();

        tenancy()->initialize($tenant);

        $this->assertDatabaseHas('inventory_items', [
            'code' => 'PC-50KG-2',
            'name' => 'Portland Cement 50kg',
        ]);

        tenancy()->end();
    }
}
